---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: velero
      version: 4.0.3
  interval: 60m0s
  releaseName: velero
  values:
    credentials:
      existingSecret: cloud-credentials
    initContainers:
      - image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-aws
        volumeMounts:
          - mountPath: /target
            name: plugins
    podAnnotations:
      ad.datadoghq.com/velero.checks: |
        {
          "openmetrics": {
            "instances": [{"metrics":["velero*"],"namespace":"openmetrics.velero","prometheus_url":"http://%%host%%:8085/metrics"}]
          }
        }
    schedules:
      backup:
        disabled: false
        schedule: 0 0 * * *
        template:
          includedNamespaces:
            - "*"
          ttl: 720h
    snapshotsEnabled: false
    tolerations:
      - effect: NoSchedule
        key: mut
        operator: Exists
      - effect: NoSchedule
        key: rrg
        operator: Exists
